#!/bin/zsh

source $HOME/.zshrc

CONDA_ENV=prf
conda activate $CONDA_ENV

cd $HOME/prf/prf

tmux new-session -s prf -d 'vim'
tmux split-window -v -t prf
tmux new-window -t prf 'jupyter notebook --notebook-dir notebooks'

tmux last-window -t prf
tmux attach-session -t prf

