#!/bin/zsh
source $HOME/.zshrc

CONDA_ENV=rs
conda activate $CONDA_ENV
export PYTHONPATH="${PYTHONPATH}:$HOME/ross/"

cd $HOME/ross/ross

tmux new-session -d 'vim'
tmux split-window -v 
tmux new-window 'jupyter notebook --notebook-dir ../notebooks'

tmux last-window
tmux -2 attach-session -d

