#!/bin/zsh
source $HOME/.zshrc

CONDA_ENV=lr
conda activate $CONDA_ENV

cd /media/raphael/My\ Passport/trabalho/material/mestrado/dissertacao/

tmux new-session -d 'vim'
tmux split-window -v 
tmux new-window 'jupyter notebook'
tmux last-window
tmux -2 attach-session -d

