#!/bin/zsh
#
source $HOME/.zshrc

CONDA_ENV=rs
conda activate $CONDA_ENV

cd $HOME/ross/ross

tmux new-session -s rs -d 'vim'
tmux split-window -v -t rs
tmux new-window -t rs 'jupyter notebook --notebook-dir ../notebooks'

tmux last-window -t rs
tmux attach-session -t rs

