#!/bin/zsh
source $HOME/.zshrc

CONDA_ENV=prf
conda activate $CONDA_ENV

cd /media/raphael/My\ Passport/TRABALHO/MATERIAL/PYTHON/prf/prf 

tmux new-session -d 'vim'
tmux split-window -v 
tmux new-window 'jupyter lab'
tmux last-window
tmux -2 attach-session -d

