#!/bin/zsh
source $HOME/.zshrc

CONDA_ENV=lr
conda activate $CONDA_ENV

cd $HOME/lavirot/lavirot

tmux new-session -d 'vim'
tmux split-window -v 
tmux new-window 'jupyter notebook --notebook-dir notebooks'
tmux last-window
tmux -2 attach-session -d

